

CREATE TABLE IF NOT EXISTS movies (
	movie_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name TEXT NOT NULL,
	rating varchar(4),
	runtime interval,
	opening_date date
);

CREATE TABLE IF NOT EXISTS theatres (
	theatre_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name TEXT NOT NULL,
	city TEXT,
	state char(2),
	owner TEXT,
	screens int
);

CREATE TABLE IF NOT EXISTS showings (
	show_id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	theatre_id int NOT NULL,
	movie_id int NOT NULL,
	tickets int NOT NULL,
	ticket_price numeric(6,2) NOT NULL,
	show_date date NOT NULL,
	show_time time NOT NULL,
	
	FOREIGN KEY (theatre_id) REFERENCES theatres(theatre_id),
	FOREIGN KEY (movie_id) REFERENCES movies(movie_id)
);
